export const generateScanScript = (): string => {
  return `#!/bin/bash

# macOS Setup Scanner
# This script scans your current Mac setup and creates a complete inventory
# Generated by DevEnv Setup Tool

set -e

OUTPUT_FILE="my-mac-scan.txt"
ARCHIVE_FILE="my-mac-setup.tar.gz"

echo "🔍 Scanning your macOS setup..."
echo ""

# Create output file
echo "# macOS Setup Scan" > "$OUTPUT_FILE"
echo "# Generated on: $(date)" >> "$OUTPUT_FILE"
echo "# Hostname: $(hostname)" >> "$OUTPUT_FILE"
echo "# macOS Version: $(sw_vers -productVersion)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Scan Homebrew packages
echo "📦 Scanning Homebrew packages..."
if command -v brew &> /dev/null; then
  echo "## HOMEBREW_FORMULAE ##" >> "$OUTPUT_FILE"
  brew list --formula >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  
  echo "## HOMEBREW_CASKS ##" >> "$OUTPUT_FILE"
  brew list --cask >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  
  echo "## HOMEBREW_TAPS ##" >> "$OUTPUT_FILE"
  brew tap >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Scan Node.js versions (nvm)
echo "📦 Scanning Node.js versions..."
if [ -d "$HOME/.nvm" ]; then
  echo "## NODE_VERSIONS ##" >> "$OUTPUT_FILE"
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  nvm list >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Scan Python versions (pyenv)
echo "📦 Scanning Python versions..."
if command -v pyenv &> /dev/null; then
  echo "## PYTHON_VERSIONS ##" >> "$OUTPUT_FILE"
  pyenv versions >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Scan Ruby versions (rbenv)
echo "📦 Scanning Ruby versions..."
if command -v rbenv &> /dev/null; then
  echo "## RUBY_VERSIONS ##" >> "$OUTPUT_FILE"
  rbenv versions >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Scan global npm packages
echo "📦 Scanning global npm packages..."
if command -v npm &> /dev/null; then
  echo "## NPM_GLOBAL ##" >> "$OUTPUT_FILE"
  npm list -g --depth=0 >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Scan pip packages
echo "📦 Scanning pip packages..."
if command -v pip3 &> /dev/null; then
  echo "## PIP_PACKAGES ##" >> "$OUTPUT_FILE"
  pip3 list >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Scan VS Code extensions
echo "📦 Scanning VS Code extensions..."
if command -v code &> /dev/null; then
  echo "## VSCODE_EXTENSIONS ##" >> "$OUTPUT_FILE"
  code --list-extensions >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Capture shell config
echo "📦 Capturing shell configuration..."
if [ -f "$HOME/.zshrc" ]; then
  echo "## ZSHRC ##" >> "$OUTPUT_FILE"
  cat "$HOME/.zshrc" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

if [ -f "$HOME/.bashrc" ]; then
  echo "## BASHRC ##" >> "$OUTPUT_FILE"
  cat "$HOME/.bashrc" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Capture git config
echo "📦 Capturing Git configuration..."
if command -v git &> /dev/null; then
  echo "## GIT_CONFIG ##" >> "$OUTPUT_FILE"
  git config --list --global >> "$OUTPUT_FILE" 2>/dev/null || echo "None" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Create archive
echo ""
echo "📦 Creating archive..."
tar -czf "$ARCHIVE_FILE" "$OUTPUT_FILE"

echo ""
echo "✅ Scan complete!"
echo ""
echo "📄 Results saved to: $OUTPUT_FILE"
echo "📦 Archive created: $ARCHIVE_FILE"
echo ""
echo "Next steps:"
echo "1. Open $OUTPUT_FILE to view your scan results"
echo "2. Upload the contents to DevEnv Setup Tool to generate your setup script"
`;
};
