import { Selection } from '@/types/tools';

export const generateSetupScript = (selection: Selection): string => {
  const { tools, customScripts } = selection;

  let script = `#!/bin/bash

# macOS Development Environment Setup Script
# Generated by DevEnv Setup Tool
# Date: ${new Date().toISOString().split('T')[0]}

set -e

echo "🚀 Starting macOS Development Environment Setup..."
echo ""

# Check if running on macOS
if [[ ! "$OSTYPE" == "darwin"* ]]; then
  echo "❌ This script is designed for macOS only."
  exit 1
fi

# Install Homebrew if not present
if ! command -v brew &> /dev/null; then
  echo "📦 Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  
  # Add Homebrew to PATH
  if [[ $(uname -m) == 'arm64' ]]; then
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/usr/local/bin/brew shellenv)"
  fi
else
  echo "✅ Homebrew already installed"
fi

echo ""
echo "📥 Installing selected tools..."
echo ""

`;

  // Group tools by type
  const brewFormulae = tools.filter(t => t.type === 'brew');
  const brewCasks = tools.filter(t => t.type === 'brew-cask');
  const customInstalls = tools.filter(t => t.type === 'custom');

  // Install brew formulae
  if (brewFormulae.length > 0) {
    script += `# Install Homebrew formulae\n`;
    script += `brew install \\\n`;
    script += brewFormulae.map(t => `  ${t.installCommand.replace('brew install ', '')}`).join(' \\\n');
    script += `\n\n`;
  }

  // Install brew casks
  if (brewCasks.length > 0) {
    script += `# Install Homebrew casks (applications)\n`;
    brewCasks.forEach(tool => {
      script += `brew install --cask ${tool.installCommand.replace('brew install --cask ', '')}\n`;
    });
    script += `\n`;
  }

  // Custom installations
  if (customInstalls.length > 0) {
    script += `# Custom installations\n`;
    customInstalls.forEach(tool => {
      script += `echo "Installing ${tool.name}..."\n`;
      script += `${tool.installCommand}\n\n`;
    });
  }

  // Custom scripts
  if (customScripts.length > 0) {
    script += `# Custom scripts and configurations\n`;
    customScripts.forEach(cs => {
      if (cs.type === 'dotfile') {
        script += `echo "Adding ${cs.name} configuration..."\n`;
        script += `cat >> ~/.zshrc << 'EOF'\n${cs.content}\nEOF\n\n`;
      } else {
        script += `echo "Running ${cs.name}..."\n`;
        script += `${cs.content}\n\n`;
      }
    });
  }

  script += `echo ""
echo "✨ Setup complete!"
echo ""
echo "Please restart your terminal or run 'source ~/.zshrc' to apply changes."
`;

  return script;
};
